version: '3'

services:
  grafana:
    hostname: grafana
    image: grafana/grafana:7.1.4
    expose:
      - 3000
    ports:
      - 3000:3000

  timescaledb:
    hostname: timescaledb
    image: timescale/timescaledb:latest-pg12
    networks:
      internal:
        aliases:
          - postgres
    expose:
      - 5432
    ports:
      - 55435:5432
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "password"
